### ISSUE TITLE
Note on Complexity

### ISSUE THREAD

**Issue by correnson** [UnixJunkie/vp-tree#17]
Very nice work !

However, VP trees are really useful for mining huge collection of data.
From a quick look at your implementation, I found two issues. One is minor, the second one is more complex.

The minor one is about `to_list` : it has at least quadratic complexity, since each right sub-tree is traversed twice, on during `to_list` and once during `List.rev_append` ; you must use a right-to-left traversal with an accumulator instead, and add each individual `vp` node with a O(1) cons on it.
Although, since VP tree are expected to be huge, a to-list function is not really useful.

The second issue is that you assume all the data is initially available into one single list, hence it must entirely fit into the memory. Of course, having initially a small list of representative points is useful for building good vantage points using their statistical distribution. But we might want to make that database huge later on.
 
A more interesting implementation would be to have an abstract layer to access and build the VP tree lazily, hence making us able to back it on disk and only caching some nodes into memory. If you look carefully at the algorithms provided in the reference paper, only a very thin slice of the VP tree is actually required to be loaded into memory when looking for some specific points. That's where VP tree are really amazing.

Although, you shall add a function to insert a new point in the VP tree.

**Comment by UnixJunkie** [comment]
On 2018/01/20 1:37, Correnson Loïc wrote:
> Very nice work !
>
> However, VP trees are really useful for mining huge collection of data.
> From a quick look at your implementation, I found two issues. One is
> minor, the second one is more complex.

What is the size, in number of points, of your intended use case?

> The minor one is about |to_list| : it has at least quadratic complexity,
> since each right sub-tree is traversed twice, on during |to_list| and
> once during |List.rev_append| ; you must use a right-to-left traversal
> with an accumulator instead, and add each individual |vp| node with a
> O(1) cons on it.

Nice catch.
I will correct it, this is a performance bug.

> Although, since VP tree are expected to be huge, a to-list function is
> not really useful.

But since the constructor is an of_list function kind, many programmers
will expect that you provide one.

> The second issue is that you assume all the data is initially available
> into one single list, hence it must entirely fit into the memory. A more
> interesting implementation would be to have an abstract layer to access
> and build the VP tree lazily, hence making us able to back it on disk
> and only caching some branch into memory.

v-p trees are a _static_ spatial indexing data structure.

And yes, my implementation assumes that all your points can fit into 
memory (and, I am sure that at CEA people can have access to a large 
memory cluster, if needed).

I have used my implementation with N x 100_000 points, without any problem.

However, my implementation is not optimal.
In Yianilos' paper, there is a "bucketized" version which might be better.
I guess buckets can be flushed to (and read from) disk.
If you can contribute such an improvement, it would be welcome.

Remember that open source is not only about getting things for free, it 
is also about giving back. ;)

> If you look carefully at the
> algorithms provided in the reference paper, only a very thin slice of
> the VP tree is actually required to be loaded into memory when looking
> for some specific points. That's where VP tree are really amazing.

I am currently working on a data structure that might be even more 
useful than vp-trees for _static_ spatial indexing:

https://github.com/UnixJunkie/bisec-tree

However, this implementation will assume that at least all your
"vantage points" will fit into memory.

> Although, you shall add a function to insert a new point in the VP tree.

I will disappoint you, but I think that I should even remove the remove 
function (pun not intended), and not add an insert function since this 
data structure is for static spatial indexing.

If you are interested in the topic (and if you need a data structure
which supports frequent update of points), this thesis looks excellent:

https://www.fi.muni.cz/~xdohnal/phd-thesis.pdf

If you have some code to efficiently compute the diameter of a large
point set, I am interested. Cf. this thread on caml-list:

https://sympa.inria.fr/sympa/arc/caml-list/2018-01/msg00044.html

Regards,
Francois.

**Comment by UnixJunkie** [comment]
Corrected.
Since to_list was used internally, this was a very useful finding. Thanks!
Note that discussion can continue here, even if the issue is closed.

**Comment by UnixJunkie** [comment]
@correnson maybe a trick can be played. If points are replaced by identifiers instead of actual coordinates, then only all you point identifiers need to fit into memory.
The distance x y function then becomes:
load from disk x as x', y as y' and return dist x' y'.
To play this trick, you only need to provide a Point functor that works like this, no code change needed in here.

**Comment by correnson** [comment]
Exact ! Indeed, we still have to build the list of all identifiers for `VP.create` function, but I think this is completely acceptable. Another solution would be to feed `VP.create` with an array, or even better, an iterator, instead of a list.

Just to friendly continue the discussion 😸 here are some additional observations.
I noticed that your implementation actually store all VP-points into an OCaml array. So, roughly speaking, your points are _already_ uniquely identified by numbers internally. Hence, one could argue that there is no need here for a functor with module type `Point` as parameter, and no need for any list/array holding all that VP-points. The only thing required is:

```
val create : quality -> size:int -> dist:(int -> int -> float) -> t
```

Foreign points (those not registered in the VP tree) are only used to compare their distance with points in the VP-tree.  Hence, it is possible to replace all parameters of type `P.t` by:

```
type pt = (int -> float) (** distance of a « foreign » point to each VP-point *) 
val neighbors: pt -> float -> t -> int list
val find : pt -> t -> int
(* and so on... *)
```

Finally remark that the functorized version can be trivially implemented upon the indexed one, providing a probably a more « natural » interface with no distinction between foreign points and VP ones.

**Comment by UnixJunkie** [comment]
I will report once I try the trick.
But I am playing with my bisector tree recently, not with this vp-tree implementation.
